server:
  port: 8084
spring:
  datasource:
  #  url: jdbc:mysql://localhost:3306/fruit_manager?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/fruit_manager?serverTimezone=GMT%2B8
    username: root
    password: root
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # 有密码填密码，没有密码不填
#    password: root
    # 连接超时时间（ms)
    timeout: 5000ms
    # 高版本springboot中使用jedis或者lettuce
    jedis:
      pool:
        # 连接池最大连接数（负值表示无限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负值无限制)
        max-wait: 5000ms
        # 最大空闲链接数
        max-idle: 8
        # 最小空闲链接数
        min-idle: 0
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true

order:
  orderExpire: 900 #15分钟后订单失效
  orderExpirePre: fruits_oId/  #redis key前缀

############################################################
#
# 日志配置
#
############################################################
logging:
  level:
    com.itheima.canal: info
  config: classpath:logback_spring.xml